Makefile

I think go test doesn't depend on binary.

Makefile: let "test" doesn't depend on "all"

---

Makefile
VERSION
main.go

build: Add version details to binary
Generate a version string containing version number and commit that the
shim logs when initialising the logger or when the user specifies
"-version".

Add version details

---

.pullapprove.yml

Change the pullapprove configuration to require two acks before a PR
can be approved (for parity with the agent).
Fixes #13.

CI: Require 2 approvals for pullapprove

---

Gopkg.lock
Gopkg.toml
agent_test.go
main.go
pipe.go
pipe_test.go
shim.go
shim_test.go
vendor/github.com/kata-containers/agent/.travis.yml
vendor/github.com/kata-containers/agent/Gopkg.lock
vendor/github.com/kata-containers/agent/agent.go
vendor/github.com/kata-containers/agent/grpc.go
vendor/github.com/kata-containers/agent/grpc_test.go
vendor/github.com/kata-containers/agent/protocols/grpc/agent.pb.go
vendor/github.com/kata-containers/agent/protocols/grpc/agent.proto
vendor/github.com/kata-containers/agent/protocols/grpc/health.pb.go
vendor/github.com/kata-containers/agent/protocols/grpc/oci.pb.go
vendor/github.com/kata-containers/agent/protocols/mockserver/mockserver.go
vendor/github.com/kata-containers/agent/reaper.go

As discused in https://github.com/kata-containers/agent/pull/72, we'll
replace guest pid with runtime generated exec id to uniquely identify
a process.

replace pid with exec id

---

Makefile

In order to install the kata-proxy binary from the Makefile, this
commit adds a new entry "install" to it.
Fixes #23

makefile: Add "install" case

---

Gopkg.lock
Gopkg.toml
main.go
terminal_linux.go
terminal_linux_test.go

This commit relies on unix package from golang instead of moby/moby
to get the terminal setup in raw mode.
Also, it fixes an issue about the terminal being set in raw mode
every time, even when STDIN was not a terminal.
Fixes #22

terminal: Properly set raw terminal only when needed

---

.ci/go-test.sh
.ci/lib.sh
Makefile

Run `go test` via the tests repositories script. This will allow all
the unit test logic to be confined to a single location and ensure
cross-repository consistency.
Fixes #33.

CI: Run central go test script

---

main.go
shim.go
shim_test.go

This commit fixes a sporadic behavior about the output returned by the
shim when the terminal is set. In this specific case, the shim should
not call into ReadStderr() because there is only one output coming out
of the terminal. And when the shim does that, we have no control over
which output is printed first. That's why using only ReadStdout() in
case of terminal is a proper solution.
Fixes #42

shim: Fix not ordered output because of stderr usage on terminal

---

main.go

Ensure log entries specify the name of the shim, not its path.
Fixes #35.

logger: Fix syslog identifier

---

main.go
main_test.go

By default, the logrus logger redirect the logs to stderr of the
shim. This happens even when the syslog hook is added, meaning logs
are both printed to stderr and the system journal.
We cannot let this happen since those logs should not be routed back
to the output of the shim, giving some weird output while you only
expect the output coming from the command executed on the container.
That's why this commit redirects those logs to a fake io.Writer called
devNull, defining a null operation, and returning instantly when the
writer is called. This leaves only the system journal being written.
Fixes #46

log: Discard logs going to stderr

---

main.go

We need the I/O to be waited for before we try to wait for the
process. If we don't do this, the WaitProcess() call can return
before all the calls to ReadStdout(), ReadStderr and CloseStdin().
This leads to the shim failure (exits) when call into CloseStdin()
for instance. This happens because WaitProcess() delete everything
related to the process from the agent. We cannot expect to do further
calls after WaitProcess() returned.
Fixes #48

shim: Fix race condition about I/O

---

.ci/run.sh
.ci/setup.sh

.ci/setup.sh will setup the environment with
latest changes to be able to execute Kata Containers.
.ci/run.sh will execute the integration tests that live
in the 'kata-containers/tests' repository.
Fixes #53.

CI: add setup.sh & run.sh to execute integration tests

---

main.go
shim.go

logging: Use logger() rather than shimLog
Don't use the logger variable directly - use the existing `logger()`
function.
Fixes #52.

Clean up logging calls

---

fatal.go
main.go
shim.go

If the shim fails due to an internal error or if it receives a fatal
signal, write a stack trace to the log and exit.
If it was started with `--debug` also dump core.
Fixes #57.

main: stacktrace/coredump on error

---

agent_test.go

Remove unused `defaultSpec`.
Fixes #60.

test: Remove unused code

---

main.go
main_test.go

Since there is a single shim process per container process, add the
container and execID to all log calls to make analysis easier.
Fixes #72.

logger: Add container + execID

---

shim.go

- Log the window width and height if the resize fails.
- Add an `fd` field showing the file descriptor when resizing the window fails.
- Be more consistent with the log messages when trying to resize the window.
Fixes #70.

Improve resize messages

---

shim.go

Fixed bug in `shim.proxyStdio()` which was unconditionally logging
errors in a couple of places, even when there wasn't one.
Fixes #68.

logging: Only log actual I/O errors

---

.ci/faketty.sh
Makefile
terminal_linux_test.go

If the test is not running in a tty, skip it.
Tty is needed by the test.
Fixes: #75
Signed-off-by: Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>

tests: skip test if tty is not available

---

.ci/lib.sh

Only use the default tests_repo url if one is not already
set.
Fixes: #64
Signed-off-by: Graham whaley <graham.whaley@intel.com>

ci: lib: allow override of tests_repo url

---

.ci/faketty.sh

Added `-e` `script(1)` argument to `.ci/faketty.sh` to ensure the caller
is notified when the script being run by `script(1)` fails.
Fixes #84.

CI: Make faketty pass return code back to caller

---

.ci/faketty.sh
.travis.yml
signals.go
terminal_darwin.go
terminal_darwin_test.go

So, there's some code duplication between `terminal_linux.go`, `terminal_linux_test.go` and `terminal_darwin.go` and `terminal_darwin_test.go`.  We can leave it as it is now, or we can refactor the code into perhaps one single `terminal.go` and then specific `terminal_linux.go` and then `terminal_darwin.go`. Refactoring will also require changing the test files. 
Lmk

signal: terminal: Changes to support build in Darwin

---

.ci/lib.sh

Now static-checks.sh needs to have the
repository name as arguments.
Fixes #90.

CI: update static-checks.sh call

---

.travis.yml

Fixes #92
Signed-off-by: Nitesh Konkar <niteshkonkar@in.ibm.com>

travis: Add support for ppc64le

---

.travis.yml

The version of `bash(1)` provided in the Travis osx environment does
not support `typeset -A`, so update it using homebrew.
Fixes #98.

CI: Update bash on Travis osx for hash support

---

main.go
main_test.go

Add an "announce" message body for the initial log entry for
consistency with the agent.
Also, add some more fields to the announcement showing details of the CLI options used to start the shim.
Fixes #96.

Improve announcement msg

---

main.go
shim.go
shim_test.go

Move tty handling to signal handler and stop ignoring `SIGWINCH` to allow this to be passed to the container workload.
Fixes #74.

signals: Allow SIGWINCH to be passed to container

---

main.go

If the max number of golang threads (GOMAXPROCS) is not set in
the environment, then set it ourselves to a small set, but
only if the host has more cpus than that max.
This avoids us taking the default (the number of host cores)
on large-core systems, which can end up with us having a lot of
idle threads generated, consuming host PID space, and thus
artificially restricting how many containers we can run
in parallel.
Fixes: #114
Signed-off-by: Graham Whaley <graham.whaley@intel.com>

threads: restrict number of golang threads if not set

---

Makefile

Build the shim binary as Position-Independent-Executable (PIE) for improved
security and compliancy with distros packaging guidelines.
Fixes: #118

shim: build as Position-Independent-Executable

---

Makefile

Add support for DESTDIR variable, to be used when installing kata-shim
in a root filesystem other than '/'.
Fixes: #120

make: add support for DESTDIR

---

main.go

Return a standard logger entry, if shimLog pointer is not yet initialized
to avoid SIGSEGV on init.
Fixes: #131

logger: log to std logger if shimLog is not yet inited

---

terminal_linux.go

gometalinter is deprecated and will be archived April '19. The
suggestion is to switch to golangci-lint which is apparently 5x faster
than gometalinter.
Partially fixes: github.com/kata-containers/runtime#1377

lint: Switch golang linter to golangci-lint

---

.ci/lib.sh

If we are testing an stable branch, we need to checkout
to the correct branch on the tests repository.
Fixes: #158.

ci: travis: checkout test repo to correct branch

---

main.go

shim is now able to read and print the agent logs, making the
debugging processes easier when `use_vsocks` is true.
fixes #171

shim: Add option to read and print the logs from the agent

---

.travis.yml
agent_test.go
terminal_darwin.go
terminal_linux.go

Update from go 1.10 to 1.11
Fixes: #163.
(cherry picked from commit 741421a89fb505128050e4ba1244113cb30fabd9)
Signed-off-by: Ganesh Maharaj Mahalingam <ganesh.mahalingam@intel.com>

travis: update go version used in travis

---

.travis.yml

osx builds on travis are failing to find linux tools like getopt and
curl. Temporarily allowing them to fail while this is being worked out.
Fixes: #183
Signed-off-by: Ganesh Maharaj Mahalingam <ganesh.mahalingam@intel.com>

CI: allow osx builds to fail

---

tracing.go

Add a log message for every trace span created, required by the tracing tests to validate tracing is working.
Fixes: #189.

trace: Add missing log message

---

Gopkg.lock
Gopkg.toml
main.go
vendor/github.com/kata-containers/agent/agent.go
vendor/github.com/kata-containers/agent/config.go
vendor/github.com/kata-containers/agent/network.go
vendor/github.com/kata-containers/agent/protocols/client/client.go

Add support for reading agent's logs from a hybrid vsock. This feature is
very useful for debugging hypervisors that don't have a socket connected to
`/dev/console`, like firecracker
fixes #209

shim/firecracker: Read agent's logs

---

tracing.go

Force Jaeger to log when it reports traces to ensure the tracing test [1] works as expected.
Fixes: #220.
[1] - https://github.com/kata-containers/tests/blob/master/tracing/tracing-test.sh

tracing: Unbreak tracing test

---

Makefile

Allow scripts overwrite PREFIX from environment in order to install shim in a
specific path
fixes #224

Makefile: overwrite PREFIX from environment

---

Makefile

Allow scripts overwrite PREFIX from environment in order to install shim in a
specific path
fixes #224

[backport 1.9] Makefile: overwrite PREFIX from environment

---

Makefile

Allow scripts overwrite PREFIX from environment in order to install shim in a
specific path
fixes #224

[backport 1.10] Makefile: overwrite PREFIX from environment

---

Makefile

This provide a flag "STRIP=yes" to strip the golang binary
Fixs: #234
Signed-off-by: Jia He <justin.he@arm.com>

make: Add support to strip the binary

---

.travis.yml

Specify golang 1.13.9 in travis file and delete call to the
`.ci/install_go.sh` script as it is not working properly
in travis environment.
Fixes: #244.

travis: specify golang version.

---

.github/workflows/add-issues-to-project.yaml
.github/workflows/move-issues-to-in-progress.yaml
tracing.go

Add GitHub actions to:
- Add newly-created issues to the issue backlog project.
- Move issues with a linked PR into the "In progress" column
of the issue backlog project.
Related: https://github.com/kata-containers/kata-containers/issues/512
Fixes: #266.

action: Add issue to project and move to "In progress" on linked PR

---

main.go
shim.go

we can' reproduce like this,
I did an exception test
1. killall -9 qemu-system-x86_64, kill katacontainers'vm, there is
only one katacontainer, so I use killall, if there are more
than one, please use kill -9 $PidOfShim.
2. Observe the kata-shim process. I expect the all the kata-shim
process to exit, but it not.
Fixes: #272
the root cause the kata-shim not exit is that kata-shim hung in s.agent.WaitProcess,  I add a timeout for WaitProcess in this pr.
Signed-off-by: Shukui Yang <keloyangsk@gmail.com>

Fix kata-shim residual
